---
- name: reload systemd
  tags:
    - cloudflared
  become: true
  systemd:
    daemon_reload: true

- name: restart cloudflared
  tags:
    - cloudflared
  become: true
  service:
    name: cloudflared
    state: restarted
...
